// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC6kNk_CgzqxLQEdNiQSxxAJ2NAnH7EDo',
    appId: '1:730167823326:web:0edc6625493b4e630aab4f',
    messagingSenderId: '730167823326',
    projectId: 'ahmed-c5aa2',
    authDomain: 'ahmed-c5aa2.firebaseapp.com',
    storageBucket: 'ahmed-c5aa2.appspot.com',
    measurementId: 'G-7Q8C57GYS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7gQrOicpw8M-fBdoC1r38VzaM1cpPv1I',
    appId: '1:730167823326:android:d09cf60feb4f1c0b0aab4f',
    messagingSenderId: '730167823326',
    projectId: 'ahmed-c5aa2',
    storageBucket: 'ahmed-c5aa2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiCvBeut0ONA4g9suxX0IfQP6uVxYKqLI',
    appId: '1:730167823326:ios:967b63417e8a55860aab4f',
    messagingSenderId: '730167823326',
    projectId: 'ahmed-c5aa2',
    storageBucket: 'ahmed-c5aa2.appspot.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiCvBeut0ONA4g9suxX0IfQP6uVxYKqLI',
    appId: '1:730167823326:ios:967b63417e8a55860aab4f',
    messagingSenderId: '730167823326',
    projectId: 'ahmed-c5aa2',
    storageBucket: 'ahmed-c5aa2.appspot.com',
    iosBundleId: 'com.example.untitled3',
  );
}
